export const FETCH_MOBILES_REQUEST = 'FETCH_MOBILES_REQUEST'
export const FETCH_MOBILES_SUCCESS = ' FETCH_MOBILES_SUCCESS'
export const FETCH_MOBILES_FAILURE = ' FETCH_MOBILES_SUCCESS'
export const MOBILES_SORT_BY_PRICE_HIGH_TO_LOW = 'MOBILES_SORT_BY_PRICE_HIGH_TO_LOW'
export const MOBILES_SORT_BY_PRICE_LOW_TO_HIGH = 'MOBILES_SORT_BY_PRICE_LOW_TO_HIGH'

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM__FROM_CART';
export const REDUCE_QUANTITY = 'REDUCE_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';

export const EMPTY_CART = 'EMPTY_CART'


